# Generated by Django 3.0.8 on 2020-07-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pioneer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Emal', 'verbose_name_plural': 'Emails'},
        ),
    ]
