# Generated by Django 3.0.8 on 2020-07-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_pioneer', '0002_auto_20200718_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Email', 'verbose_name_plural': 'Emails'},
        ),
    ]
