# Generated by Django 3.0.8 on 2020-07-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pioneer', '0003_auto_20200718_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language_ru',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='intro',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='blog',
            name='main_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.TextField(blank=True, max_length=254),
        ),
    ]
