# Generated by Django 3.0.8 on 2020-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pioneer', '0004_auto_20200719_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=450),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
