# Generated by Django 3.0.8 on 2020-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pioneer', '0005_auto_20200719_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='language_ru',
            field=models.BooleanField(default=True),
        ),
    ]
