# Generated by Django 3.0.8 on 2020-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pioneer', '0006_email_language_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_en',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='date_ru',
            field=models.TextField(default='g'),
            preserve_default=False,
        ),
    ]
